---
- name: playbook to show error handling
  hosts: db
  become: true
  vars:
   ### http - to make it fail
    web_package: http
    db_package: mariadb-server
    db_service: mariadb

  tasks:
  - block:
    - name: check {{ web_package }} is installed
      command: yum list installed "{{ web_package }}"
      register: command_result

    - name: install {{ web_package }}
      package:
        name:  "{{ web_package }}"
        state: latest
  
    rescue:
      - name: install {{ db_package }}
        package:
          name:  "{{ db_package }}"
          state: latest
      #when: "'Error' in command_result.stdout"
      #changed_when: "command_result.rc == 1"

    always:
      - name: start {{ db-service }} db
        service:
          name: "{{ db_service }}"
          state: started
