---
- name: playbook to install db package if / is > 5G
  hosts: db
  become: true
  tasks:
    - name: isntall db package if / is > 5G
      package: 
        name: mariadb-server
        state: installed
      with_items: "{{ ansible_mounts }}"
      when: item.mount == "/" and item.size_available > 5000000000

    - name: start db
      service: 
        name: mariadb
        state: started
        enabled: yes
      
