---
- name: playbook to install vsftp and firewalld on web servers
  hosts: web
  remote_user: ec2-user
  become: true
  become_user: root
  become_method: sudo
  tasks:
    - name: install packages
      package: 
        name: "{{ item }}"
        state: latest
      with_items:
        - vsftpd
        - firewalld

    - name: allow ftp service
      firewalld:
        service: ftp
        permanent: yes
        state: enabled
        immediate: yes

    - name: enable services
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - vsftpd
        - firewalld

