---
# tasks file for myfirewall

- name: install firewall
  package: 
    name: firewalld
    state: present

- name: start and enable fw
  service:
    name: firewalld
    state: started
    enabled: yes

- name: enable service ports
  firewalld:
    service: "{{ fw_service }}"
    state: enabled
    immediate: yes
    permanent: yes 
