---
- name: reboot a server
  hosts: db
  tasks:
    - name: restart servers
      shell: sleep 2 && reboot -f
      async: 1
      poll: 0
      ignore_errors: true

    - name: waiting for server to be back
      wait_for: 
        host: "{{ inventory_hostname }}"
        state: started
        delay: 30
        timeout: 300
        port: 22
      delegate_to: localhost
