---
- name: create users
  hosts: all
  become: true
  vars_files:
    - vars/secret.yml
  tasks:
  - name: create user
    user:
      name: "{{ item.name }}"
      password: "{{ item.pw | password_hash('sha512') }}"
    with_items: "{{ newusers }}"
